# 名称：Release 发布流程
# name: Release # 工作流名称

# permissions: # 权限声明
#   contents: write # 允许写入仓库内容
#   id-token: write # 允许写入ID令牌

# on: # 触发条件
#   workflow_dispatch: # 手动触发
#     inputs:
#       increment: # 版本号递增类型
#         required: true # 必填
#         default: patch # 默认patch
#         type: choice # 选项类型
#         options:
#           - major # 主版本
#           - minor # 次版本
#           - patch # 修订号

# jobs: # 工作任务定义
#   release: # 任务名
#     runs-on: ubuntu-latest # 运行环境
#     steps: # 步骤
    # 以下步骤已注释，暂不执行实际动作
    #     - uses: actions/checkout@v4 # 拉取代码
    #       with:
    #         fetch-depth: 0 # 拉取全部历史，便于发布
    #         token: ${{ secrets.RELEASE_TOKEN }} # 使用私密令牌
    #     - name: Git config # 配置Git用户信息
    #       run: |
    #         git config user.name "github-actions[bot]"
    #         git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    #     - name: Set node # 设置Node环境
    #       uses: actions/setup-node@v4
    #       with:
    #         node-version: lts/* # 使用最新LTS
    #         registry-url: 'https://registry.npmjs.org' # NPM官方源
    #     - name: Install pnpm # 安装pnpm
    #       uses: pnpm/action-setup@v3
    #       with:
    #         run_install: |
    #           - args: [--frozen-lockfile] # 严格锁定依赖
    #     - name: Release # 执行发布
    #       run: npx release-it ${{ inputs.increment }} --verbose # 调用release-it发布
    #       env:
    #         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # GitHub令牌
    #         CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }} # Chrome扩展ID
    #         CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
    #         CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
    #         CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
    #         FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }} # Firefox扩展ID
    #         FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
    #         FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
    #         EDGE_PRODUCT_ID: ${{ secrets.EDGE_PRODUCT_ID }} # Edge扩展ID
    #         EDGE_CLIENT_ID: ${{ secrets.EDGE_CLIENT_ID }}
    #         EDGE_CLIENT_SECRET: ${{ secrets.EDGE_CLIENT_SECRET }}
    #         EDGE_ACCESS_TOKEN_URL: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}
